### ISSUE TITLE
Unable to interrupt walking

### ISSUE THREAD

**Issue by stefanengel** [tfelix/bestia-client#1]
Hi there,

when I click on point A, the character starts walking there. When I click on point B before the character has reached point A, the click is ignored.

Expected behaviour: the walk to point A is interrupted as soon as the player clicks on point B and the character walks to point B instead.

**Comment by tfelix** [comment]
Your right. This is currently a bug. sadly a quite hard one to fix. But lets see what we can do. Movement data is reset during the callback from the movement tween. Even deleting the data does not prevent it from coming back.

**Comment by tfelix** [comment]
Movement is still not perfect since the transition is a bit rough but works for now I guess.
